kind: pipeline
name: default
steps:
  - name: Hello World
    image: alpine
    environment:
      DEPLOY_DIR:
        from_secret: DEPLOY_DIR
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
      - $DEPLOY_DIR:/root/docker
    commands:
    - ls /root/docker
volumes: # 定义流水线挂载目录，用于共享数据
  - name: test-v
    host:
      path: ${DEPLOY_DIR}